require:
  - rubocop
  - rubocop-faker

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - Guardfile
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - components/courses/db/migrate/*
    - components/courses/spec/dummy/**/*
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  ExcludedMethods: [
    'describe', 'xdescribe', 'context', 'xcontext', 'it', 'xit', 'get', 'post', 'put', 'FactoryBot.define',
    'factory', 'let', 'before', 'after', 'configure',  'resource', 'aggregate_failures', 'draw', 'collection',
    'example'
  ]
