inherit_from: .rubocop_todo.yml

require:
  - rubocop
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/Rails/HttpStatus:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6.9
  NewCops: enable
  Exclude:
    - Guardfile
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - components/courses/db/migrate/*
    - components/courses/spec/dummy/**/*
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/lib/dry_helpers/model_spec.rb'

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: [
    'describe', 'xdescribe', 'context', 'xcontext', 'it', 'xit', 'get', 'post', 'put', 'FactoryBot.define',
    'factory', 'let', 'before', 'after', 'configure',  'resource', 'aggregate_failures', 'draw', 'collection',
    'example'
  ]

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/admin/events_controller.rb'
    - 'app/controllers/admin/friends_controller.rb'
    - 'app/controllers/admin/groups_controller.rb'
    - 'app/controllers/admin/members_controller.rb'
    - 'app/controllers/admin/pages_controller.rb'
    - 'app/controllers/admin/talks_controller.rb'
    - 'app/controllers/admin/venues_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/admin/application_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/events_helper.rb'
    - 'app/inputs/date_time_input.rb'
    - 'app/inputs/image_preview_input.rb'
    - 'app/services/markdown_renderer.rb'
Rails/SkipsModelValidations:
  AllowedMethods: ['upsert']