#!/bin/sh
echo "Creating pivorak_production database\n";
psql -h postgres -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'pivorak_production'" | grep -q 1 || psql -h postgres -U postgres -c "CREATE DATABASE pivorak_production WITH OWNER postgres ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE template0;"
