---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
production:
  :concurrency: 20
:queues:
  - default
  - mailers

:schedule:
  FetchAllTalksDataJob:
    every: '1d' # Runs every day
    class: FetchAllTalksDataJob
