name: Pivorak CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_COMPOSE_VERSION: 1.24.0
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Compose
      run: |
        curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin
        docker-compose --version
    
    - name: Build Compose
      run: |
        docker-compose build
        docker-compose run runner bundle install --jobs=3 --retry=3 --deployment
    
    - name: Prepare Database
      run: |
       cp config/database.yml.example config/database.yml
       docker-compose run -e RAILS_ENV=test runner bundle exec rails db:create db:schema:load
    
    - name: Test Application
      run: |
        docker-compose run runner bundle exec rubocop
        docker-compose run runner bundle exec rspec
      
      
